name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Start web server
        run: npm start &
        env:
          CI: true

      - name: Wait for server to start
        run: sleep 5

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CI: true

      - name: Stop web server
        run: npm stop
